### ISSUE TITLE
doc: Rename+mv "ClientUseDefaultPort"

### ISSUE THREAD

**Issue by dylanh724** [James-Frowen/SimpleWebTransport#6]
At first glance, this looks undesirable (and confusing). However, after looking at the tooltip, one with a reverse proxy may realize that nothing works because this isn't checked :)

This is such an overwhelmingly important feature that it can easily be overlooked in its current name. 

Instead of this name and location under port, it should probably go right underr "Server Settings" 'at top and center.

The rename is debatable, but should probably be something similar to `ReverseProxy`. An explicit tooltip example mentioning "Nginx" may turn some heads to importance, as well. Heck ,it could be `ReverseProxyUseDefaultPort` if it's truly believed "default port" keyword would help folks (to me, it meant "ignore the port I listed above").

**Comment by James-Frowen** [comment]
I'd rather not rename the field because that would be a breaking change for people currently using it. 

What it basically does is leave off the port from the URI, so that it uses the default port. but I guess that can be a bit confusing without knowing that http/websockets use port 80 (or 443 for https).

I think improving the docs for Reverse Proxy to mention this field would probably help things.
